site_name: Wiki | Scene.RE
site_description: Recopilación de información que puede ser relevante o no, sin ninguna categoría en particular
strict: true
site_url: https://wiki.scene.re/

copyright: <a href="https://github.com/SceneRE/wiki/blob/main/LICENSE" target="_blank" rel="noopener">Sin derechos reservados / No rights reserved - 2022</a>

theme:
  name: material
  language: es
  icon:
    logo: simple/knowledgebase
  custom_dir: customs
  palette:
    scheme: slate
    primary: deep purple

repo_name: SceneRE/wiki
repo_url: https://github.com/SceneRE/wiki
edit_uri: edit/main/docs/

extra:
  analytics:
    provider: google
    property: G-19J4G4SPKZ
    feedback:
      title: ¿Fue útil esta página?
      ratings:
        - icon: material/emoticon-happy-outline
          name: Esta página fue útil
          data: 1
          note: >-
            ¡Gracias por sus comentarios!
        - icon: material/emoticon-sad-outline
          name: Esta página podría mejorarse
          data: 0
          note: >- 
            ¡Gracias por tus comentarios! Ayúdanos a mejorar esta página <a href="https://github.com/SceneRE/wiki/discussions" target="_blank" rel="noopener">creando una discusión</a>.

markdown_extensions:
  - admonition

plugins:
  - search